### ISSUE TITLE
steam identifier

### ISSUE THREAD

**Issue by imZesk** [Birkegud/TerminatorAC#1]
Hi, thanks for your amazing contribution, but I dont know how to find the steam identifier to add a bypass.

**Comment by Birkegud** [comment]
There are sites like https://steamidfinder.com/lookup/ you can use to find your steam id. 
![image](https://user-images.githubusercontent.com/73035583/110218457-2c77d600-7eba-11eb-9f5f-4a3647f01f68.png)
