### ISSUE TITLE
Lux menu bypass

### ISSUE THREAD

**Issue by imZesk** [Birkegud/TerminatorAC#3]
An old menu called lux that is public and embed in redengine executor is bypassing the Anticheat.

https://github.com/leuit/lux-menu

also here is the menu d0pamine leaked by the dev too https://github.com/nertigel/d0pamine_lua

**Comment by Birkegud** [comment]
That's why you need to configure the config so it cant bypass. I haven't made a proper config yet

**Comment by Birkegud** [comment]
For example "LuxUI" is a global table and therefore you can detect it

**Comment by imZesk** [comment]
Oh ok I catch you thanks mate!

**Comment by imZesk** [comment]
The LuxUI is a GlobalVarDetection or FunctionDetection

**Comment by Birkegud** [comment]
If you aint sure just put Them in both. But its for glibalvardetection
